-- ================================================================
--  장소 접수 -> 택시 배차  통합 접수 데스크
--  Supabase SQL Editor 에 통째로 붙여 넣고 Run 하세요.
--  값은 WoS(Wizard of Seoul) 관광+택시 대화 1,297건에서 뽑은 것입니다.
-- ================================================================


-- ----------------------------------------------------------------
--  1. 장소 사전  (자동 조회용)
--
--     유저에게 묻지 않는 칸의 출처입니다.
--     이름이 정해지면 주소 / 연락처 / 평점이 여기서 따라옵니다.
-- ----------------------------------------------------------------
drop table if exists place_directory cascade;

create table place_directory (
  name    text primary key,
  type    text not null,          -- 관광-종류
  area    text not null,          -- 관광-지역
  address text,
  phone   text,
  rating  numeric(2,1)
);

insert into place_directory (name, type, area, address, phone, rating) values
  ('N 서울 타워',        '랜드마크', '서울 중앙', '서울 용산구 남산공원길 105',   '02-3455-9277', 4.5),
  ('광화문 광장',        '랜드마크', '서울 북쪽', '서울 종로구 세종대로 172',     '02-2133-2657', 4.4),
  ('남산골 한옥 마을',   '랜드마크', '서울 중앙', '서울 중구 퇴계로34길 28',      '02-2261-0517', 4.3),
  ('동대문 (흥인지문)',  '랜드마크', '서울 북쪽', '서울 종로구 종로 288',         '02-2148-1807', 4.2),
  ('러브뮤지엄',         '박물관',   '서울 서쪽', '서울 마포구 양화로 162',       '02-333-3211',  3.8),
  ('롯데월드 아쿠아리움','동물원',   '서울 동쪽', '서울 송파구 올림픽로 300',     '1661-2000',    4.4),
  ('롯데월드타워&몰',    '쇼핑',     '서울 동쪽', '서울 송파구 올림픽로 300',     '1661-2000',    4.6),
  ('봉은사',             '랜드마크', '서울 남쪽', '서울 강남구 봉은사로 531',     '02-3218-4800', 4.5),
  ('북악산 서울 성곽',   '랜드마크', '서울 북쪽', '서울 종로구 창의문로 118',     '02-730-9924',  4.4),
  ('삼청각',             '랜드마크', '서울 북쪽', '서울 성북구 대사관로 3',       '02-765-3700',  4.2),
  ('삼청동길',           '랜드마크', '서울 북쪽', '서울 종로구 삼청로 일대',      '02-2148-1114', 4.3),
  ('서울스카이',         '랜드마크', '서울 동쪽', '서울 송파구 올림픽로 300',     '1661-2000',    4.6),
  ('서울중앙성원',       '랜드마크', '서울 중앙', '서울 용산구 우사단로10길 39',  '02-793-6908',  4.3),
  ('석촌호수',           '공원',     '서울 동쪽', '서울 송파구 삼학사로 136',     '02-412-0190',  4.5),
  ('세종대왕 동상',      '랜드마크', '서울 북쪽', '서울 종로구 세종대로 175',     '02-2133-2641', 4.4),
  ('신세계 백화점 본점', '쇼핑',     '서울 중앙', '서울 중구 소공로 63',          '1588-1234',    4.4),
  ('신촌',               '기타',     '서울 북쪽', '서울 서대문구 신촌로 일대',    '02-330-1114',  4.0),
  ('예술의전당',         '박물관',   '서울 남쪽', '서울 서초구 남부순환로 2406',  '02-580-1300',  4.6),
  ('운현궁',             '랜드마크', '서울 북쪽', '서울 종로구 삼일대로 464',     '02-766-9090',  4.2),
  ('익선동한옥거리',     '기타',     '서울 북쪽', '서울 종로구 수표로28길 일대',  '02-2148-1114', 4.3),
  ('청와대',             '랜드마크', '서울 북쪽', '서울 종로구 청와대로 1',       '02-3701-7200', 4.5),
  ('코엑스 아쿠아리움',  '동물원',   '서울 남쪽', '서울 강남구 영동대로 513',     '02-6002-6200', 4.3),
  ('하늘공원',           '공원',     '서울 서쪽', '서울 마포구 하늘공원로 95',    '02-300-5501',  4.5),
  ('홍대앞 거리',        '랜드마크', '서울 서쪽', '서울 마포구 양화로 일대',      '02-3153-8114', 4.2);


-- ----------------------------------------------------------------
--  2. 접수  (한 건 = 장소 1 + 택시 1)
--
--     두 도메인이 한 행에 같이 삽니다.
--     이것이 "두 도메인을 처리하는 하나의 서비스" 의 실체입니다.
--
--     묻는 칸 7개   place_type, place_area, place_name,
--                   taxi_from, taxi_to, taxi_depart_at, taxi_class
--                   (출발지·도착지 중 한 칸은 taxi_link 에 따라 장소에서 자동으로 옵니다)
--     자동 칸 4개   place_address, place_phone, place_rating, driver_phone
-- ----------------------------------------------------------------
drop table if exists booking cascade;

create table booking (
  id              uuid primary key default gen_random_uuid(),
  ref             bigint generated by default as identity,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- 관광 : 묻는 칸
  place_type      text,
  place_area      text,
  place_name      text references place_directory(name),

  -- 관광 : 자동 칸
  place_address   text,
  place_phone     text,
  place_rating    numeric(2,1),

  -- 택시 : 묻는 칸
  taxi_from       text,
  taxi_to         text,
  taxi_depart_at  text,
  taxi_class      text,

  -- 두 도메인이 이어지는 방식
  --   'from' 장소에서 출발한다  -> taxi_from  이 place_name 을 받습니다  (데이터의 47%)
  --   'to'   장소로 도착한다    -> taxi_to    가 place_name 을 받습니다  (데이터의 24%)
  --   'none' 택시는 딴 데로 간다 -> 두 칸 다 직접 받습니다               (데이터의 29%)
  --
  --   비율은 WoS 관광+택시 대화에서 실제로 센 것입니다.
  --   장소를 도착지로 고정하면 24% 만 맞습니다.
  taxi_link       text not null default 'from',

  -- 택시 : 자동 칸
  driver_phone    text,

  status          text not null default 'draft',
  revision        int  not null default 0
);

create index booking_created_idx on booking (created_at desc);


-- ----------------------------------------------------------------
--  3. 변경 이력
--
--     "수정 시나리오" 9개의 채점표가 됩니다.
--     사람이 직접 고친 칸과, 그 때문에 딸려 바뀐 칸을 구분해 남깁니다.
-- ----------------------------------------------------------------
drop table if exists booking_change cascade;

create table booking_change (
  id          bigint generated by default as identity primary key,
  booking_id  uuid not null references booking(id) on delete cascade,
  changed_at  timestamptz not null default now(),
  field       text not null,
  old_value   text,
  new_value   text,
  cascaded    boolean not null default false   -- true = 사람이 안 건드렸는데 따라 바뀐 칸
);

create index booking_change_booking_idx on booking_change (booking_id, changed_at);


-- ----------------------------------------------------------------
--  4. updated_at 자동 갱신
-- ----------------------------------------------------------------
create or replace function touch_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger booking_touch
  before update on booking
  for each row execute function touch_updated_at();


-- ----------------------------------------------------------------
--  5. 접근 권한 (RLS)
--
--     중요 - anon key 는 비밀이 아닙니다.
--     브라우저에 내려가는 값이라 페이지를 여는 누구나 볼 수 있습니다.
--     .env 로 감추는 것은 저장소 이력에 안 남기려는 것이지,
--     배포된 사이트를 지켜 주지는 않습니다.
--     실제로 데이터를 지키는 것은 아래 정책입니다.
--
--     로그인이 없는 실습이라 접수는 누구나 넣고 고칠 수 있습니다.
--     대신 지우기와 장소 사전 쓰기는 막아 둡니다.
--     발표가 끝나면 프로젝트를 지우거나 로그인을 붙이세요.
-- ----------------------------------------------------------------
alter table place_directory enable row level security;
alter table booking         enable row level security;
alter table booking_change  enable row level security;

-- 장소 사전 - 읽기만. 아무도 못 고칩니다.
create policy "장소 읽기" on place_directory
  for select using (true);

-- 접수 - 읽기 / 넣기 / 고치기. 지우기는 정책이 없으므로 막힙니다.
create policy "접수 읽기"   on booking for select using (true);
create policy "접수 넣기"   on booking for insert with check (true);
create policy "접수 고치기" on booking for update using (true) with check (true);

-- 변경 이력 - 읽기 / 넣기. 고치기와 지우기는 막힙니다. 이력은 남아야 합니다.
create policy "이력 읽기" on booking_change for select using (true);
create policy "이력 넣기" on booking_change for insert with check (true);


-- ----------------------------------------------------------------
--  확인
-- ----------------------------------------------------------------
select count(*) as 장소_건수 from place_directory;
